package:
  name: openmm-cuda{{ CUDA_SHORT_VERSION }}
  version: 7.2.2

source:
  git_url: https://github.com/pandegroup/openmm.git
  git_tag: 32bc79a

build:
  number: 0
  skip: True # [win]
  script_env:
    - CUDA_VERSION
    - CUDA_SHORT_VERSION

requirements:
  build:
    - cmake
    - python
    - fftw3f ==3.3.3
    # swig is pinned to use omnia swig 3.0.8
    - swig ==3.0.8
    - doxygen
    - sphinx
    - sphinxcontrib-bibtex
    - sphinxcontrib-lunrsearch
    - sphinxcontrib-autodoc_doxygen
    - lxml
    - numpy
    - clangdev ==6.0.0

  run:
    - python
    - fftw3f
    - numpy

test:
  requires:
    - python
  imports:
    - simtk
    - simtk.openmm
  commands:
    - python -m simtk.testInstallation

about:
  home: http://openmm.org
  license: LGPL and MIT
  summary: A high performance toolkit for molecular simulation.
